<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AssemblyName>MessengeR</AssemblyName>
    <AssemblyTitle>MessengeR</AssemblyTitle>
    <Product>MessengeR</Product>
    <Description>MessengeR Desktop App for Windows</Description>
    <Version>2026.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="icon.ico" />
    <Resource Include="icon.png" />
    <None Update="icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="web_installer\**" />
    <Page Remove="web_installer\**" />
    <Resource Remove="web_installer\**" />
    <None Remove="web_installer\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.1.3" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4258.31" />
  </ItemGroup>

</Project>
